GRANT USAGE ON DATABASE ANALYTICS TO ROLE BI_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE BI_ANALYST;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE BI_ANALYST;
GRANT SELECT ON VIEW ANALYTICS.MARTS.VW_REVENUE_ORDER_LINE TO ROLE BI_ANALYST;
GRANT SELECT ON VIEW ANALYTICS.MARTS.VW_REVENUE_DAILY_REGION TO ROLE BI_ANALYST;
GRANT SELECT ON VIEW ANALYTICS.MARTS.VW_DIM_CUSTOMER TO ROLE BI_ANALYST;
GRANT SELECT ON VIEW ANALYTICS.MARTS.VW_DIM_PRODUCT TO ROLE BI_ANALYST;
