-- Grain: one row per day × region (overview aggregation for cheap live queries)
CREATE OR REPLACE SECURE VIEW VW_REVENUE_DAILY_REGION AS
SELECT
    ORDER_DAY,
    REGION_NAME,
    COUNTRY_CODE,
    SUM(NET_REVENUE)   AS NET_REVENUE,
    SUM(COGS)          AS COGS,
    SUM(GROSS_MARGIN)  AS GROSS_MARGIN,
    SUM(QUANTITY)      AS QUANTITY,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
FROM MARTS.VW_REVENUE_ORDER_LINE
GROUP BY 1, 2, 3;
