name: supply_chain_control_tower
version: 1.0.0
config-version: 2
profile: supply_chain_control_tower
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
models:
  supply_chain_control_tower:
    staging: { +materialized: view }
    intermediate: { +materialized: view }
    marts: { +materialized: table }
